# Generated by Django 3.0.6 on 2020-05-15 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('green_blog_main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='user',
            new_name='author',
        ),
    ]
