# Generated by Django 3.0.6 on 2020-05-15 06:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('green_blog_main', '0002_auto_20200515_1114'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Posts123',
        ),
    ]
