# Generated by Django 3.0.6 on 2020-05-15 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('green_blog_main', '0005_auto_20200515_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='date',
            new_name='blog_date',
        ),
    ]
